// Generate the subsetted WOFF2 web fonts in public/fonts from Inter's source TTFs.
//
// Why: the five TTFs are 1.59 MB on disk and ~956 KB actually transferred —
// 67% of the page weight, and TTF barely gzips. WOFF2 uses Brotli internally,
// and subsetting to the characters this dashboard can actually render drops it
// again. The @font-face rules get a unicode-range matching the subset, so any
// character outside it (CJK in a future chain name) falls back to a system
// font rather than rendering tofu.
//
// Run manually when the fonts or the glyph inventory change; the .woff2 files are
// committed artifacts, not a build step. `subset-font` is deliberately NOT a dependency
// of this project — it is needed only by this script, a handful of times ever, so install
// it for the run and drop it again:
//
//   npm i --no-save subset-font && node scripts/buildfonts.mjs
//
// The source .ttf files are no longer committed (that was the 1.59 MB this removed); fetch
// the Inter release matching the version in the @font-face comment before regenerating.
import subsetFont from 'subset-font';
import { readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const SRC = join(dirname(fileURLToPath(import.meta.url)), '..', 'public', 'fonts');

// Weights actually used by the stylesheet (verified: 300 and 500 are dead;
// 550/650 are not declared anywhere and silently resolve to 600/700).
const WEIGHTS = [400, 600, 700];

// The glyph inventory: Basic Latin + Latin-1 Supplement + Latin Extended-A
// (accented chain names), plus the specific punctuation and symbols the UI
// draws. Anything not listed here falls back to a system font by unicode-range.
const ranges = [
    [0x0020, 0x007e],   // Basic Latin
    [0x00a0, 0x00ff],   // Latin-1 Supplement
    [0x0100, 0x017f]    // Latin Extended-A (ū, ł, ő …)
];
const EXTRA = [
    0x2010, 0x2011, 0x2012, 0x2013, 0x2014, // hyphens / en / em dash
    0x2018, 0x2019, 0x201c, 0x201d,         // curly quotes
    0x2022, 0x2026,                         // bullet, ellipsis
    0x00b7, 0x00d7,                         // middot, multiplication sign
    0x2039, 0x203a,                         // ‹ ›
    0x2190, 0x2192, 0x2191, 0x2193,         // arrows (legend text)
    0x2212, 0x2264, 0x2265,                 // minus, <=, >=
    0x25b2, 0x25bc,                         // sort carets ▲ ▼
    0x2713, 0x2717,                         // ✓ ✗ (assistant trace)
    0x00a9, 0x00ae, 0x2122                  // © ® ™
];

let text = '';
for (const [a, z] of ranges) for (let c = a; c <= z; c++) text += String.fromCodePoint(c);
for (const c of EXTRA) text += String.fromCodePoint(c);

// unicode-range for the @font-face rule, mirroring the subset above.
const unicodeRange = [
    'U+0020-007E', 'U+00A0-00FF', 'U+0100-017F',
    'U+2010-2014', 'U+2018-2019', 'U+201C-201D', 'U+2022', 'U+2026',
    'U+00B7', 'U+00D7', 'U+2039-203A', 'U+2190-2193',
    'U+2212', 'U+2264-2265', 'U+25B2', 'U+25BC', 'U+2713', 'U+2717',
    'U+00A9', 'U+00AE', 'U+2122'
].join(', ');

const report = [];
for (const w of WEIGHTS) {
    const src = `${SRC}/inter-${w}.ttf`;
    const buf = await readFile(src);
    const out = await subsetFont(buf, text, { targetFormat: 'woff2' });
    await writeFile(`${SRC}/inter-${w}.woff2`, out);
    report.push({ weight: w, ttfKB: +(buf.length / 1024).toFixed(1), woff2KB: +(out.length / 1024).toFixed(1) });
}

const css = `/* Generated by scripts/buildfonts.mjs — do not hand-edit.
 *
 * Subsetted WOFF2 replaces five 318 KB TTFs (1.59 MB, ~956 KB transferred).
 * Only the weights the stylesheet uses are shipped: 400 (body), 600 (headings,
 * labels), 700 (emphasis). Weight 300 and 500 were declared but never used.
 *
 * unicode-range matches the subset (Latin + the punctuation this UI draws), so
 * a character outside it falls back to a system font instead of tofu.
 *
 * font-display: swap — text paints immediately in the fallback and swaps when
 * Inter arrives, so a slow font never blocks first paint.
 */
${WEIGHTS.map(w => `@font-face {
  font-family: 'Inter';
  font-style: normal;
  font-weight: ${w};
  font-display: swap;
  src: url(inter-${w}.woff2) format('woff2');
  unicode-range: ${unicodeRange};
}`).join('\n')}
`;
await writeFile(`${SRC}/inter.css`, css);

const ttfTotal = report.reduce((s, r) => s + r.ttfKB, 0);
const w2Total = report.reduce((s, r) => s + r.woff2KB, 0);
console.log(JSON.stringify({
    perWeight: report,
    shippedBefore_5xTTF_KB: 1590,
    shippedNow_3xWOFF2_KB: +w2Total.toFixed(1),
    savingVsThreeTTF: `${ttfTotal.toFixed(0)}KB -> ${w2Total.toFixed(1)}KB`,
    reductionPct: +((1 - w2Total / 1590) * 100).toFixed(1)
}, null, 1));
